{% set name = "scrapy-playwright" %}
{% set version = "0.0.43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scrapy_playwright-{{ version }}.tar.gz
  sha256: a60f680af1080c86b1f128a4453bd3eb761864bea58c116f89a60ba2dd65c8f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - scrapy >=2.0,!=2.4.0
    - playwright-python >=1.15

test:
  imports:
    - scrapy_playwright
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scrapy-plugins/scrapy-playwright
  summary: Playwright integration for Scrapy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - luftuq
