{% set name = "scrapy-playwright" %}
{% set version = "0.0.44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scrapy_playwright-{{ version }}.tar.gz
  sha256: e2200610d5619cc08c747484810efc55bc88de00324e2ccf5a1f74942295243e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - scrapy >=2.0,!=2.4.0
    - playwright-python >=1.15

test:
  imports:
    - scrapy_playwright
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scrapy-plugins/scrapy-playwright
  summary: Playwright integration for Scrapy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - luftuq
